server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        - id: farmer-service
          uri: lb://farmer-service
          predicates:
            - Path=/farmers/**, /vouchers/**, /farmerCategories/**, /counties/**, /doctor-service/v3/api-docs

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/** , /product-service/v3/api-docs

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/messages/** , /notification-service/v3/api-docs

        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/**, /oauth2/**, /roles/**, /profile/**, /privileges/**, /institutions/**, /user-management-service/v3/api-docs
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service

      - url: /farmer-service/v3/api-docs
        name: Farmer Service
        primaryName: Farmer Service

      - url: /product-service/v3/api-docs
        name: Product Service
        primaryName: Product Service

      - url: /notification-service/v3/api-docs
        name: Notification Service
        primaryName: Notification Service

      - url: /user-management-service/v3/api-docs
        name: User Management Service
        primaryName: User management Service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
