server:
  servlet:
    context-path: /
  port:
    8083

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/farmbase-v1
    username: postgres
    password: 19pool90

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    bootstrap:
      enabled: true

  liquibase:
    change-log: 'classpath:/db/changelog/liquibase.change-log.xml'

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: 'false'


openapi:
  service:
    title: product-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /product-service/v3/api-docs
  swagger-ui:
    path: /product-service/swagger-ui.html
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
